server:
  port: 8083  
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka 
    instance:
      hostname: eureka-server      

spring:  
  cloud:
    gateway:
      routes:
        - id: backend-resources          
          uri: lb://backend-resources
          predicates:
            Path=/messages/**
          filters:
            TokenRelay=
            
  security:
    oauth2:
      client:
        registration:
           keycloak:
            provider: my-keycloak-provider
            client-id: spring-gateway-client
            client-secret: mVGQDpvWkeOYrx3obNBjRkWzFIddoJlT
            authorization-grant-type: authorization_code
            redirect-uri: "http://192.168.100.12:8083/login/oauth2/code/keycloak" 
            scope: openid        
        provider:         
          my-keycloak-provider:
            issuer-uri: http://192.168.100.12:8080/auth/realms/myRealm
