server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://host.docker.internal:8761/eureka 
    instance:
      hostname: 192.168.100.12
      nonSecurePortEnabled: false
      securePortEnabled: true
      securePort: 8765
      prefer-ip-address: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: producer-service
          uri: lb://producer-service
          predicates:
            - Path=/producer/**
        - id: listener-service
          uri: lb://listener-service
          predicates:
            - Path=/login/** , /auth/**
          filters:
            - StripPrefix=1  