server:
  port: 8081
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    prefer-ip-address: true
    service-url:
      default-zone: http://192.168.100.12:8761/eureka
    instance:
      hostname: 192.168.100.12

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: producer-service
          uri: lb://producer-service
          predicates:
            - Path=/producer/**
        - id: listener-service
          uri: lb://listener-service
          predicates:
            - Path=/login/** , /auth/**
          filters:
            - StripPrefix=1  