server:
  port: 8080
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: producer-service
          uri: lb://producer-service
          predicates:
            - Path=/producer/**
        - id: listener-service
          uri: lb://listener-service
          predicates:
            - Path=/login/** , /auth/**
          filters:
            - StripPrefix=1  